# -*- coding: utf-8 -*-
"""GenerateNeighbours&TSPDistance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKUgVLn0zrqiXQmC7xTkL_oiQGocZ3uF
"""

import math
import random

# 1. Hàm tính khoảng cách Euclid giữa hai thành phố a và b
def distance(a, b):
    # Công thức: sqrt((x2-x1)^2 + (y2-y1)^2)
    return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2)

# 2. Hàm tính tổng quãng đường của toàn bộ lộ trình (TSP Distance)
def compute_tsp_distance(tour, cities):
    total = 0
    n = len(tour)
    for i in range(n):
        city_a = cities[tour[i]]
        # tour[(i + 1) % n] giúp nối thành phố cuối cùng về lại thành phố đầu tiên
        city_b = cities[tour[(i + 1) % n]]
        total += distance(city_a, city_b)
    return total

def get_neighbor(tour, cities):
    n = len(tour)
    # Chọn ngẫu nhiên hai vị trí i và j để thực hiện đảo đoạn
    i = random.randint(0, n - 2)
    j = random.randint(i + 1, n - 1)

    # Tính toán chênh lệch khoảng cách (delta_e) thay vì tính lại từ đầu
    a = tour[i - 1] if i > 0 else tour[-1]
    b = tour[i]
    c = tour[j]
    d = tour[j + 1] if j < n - 1 else tour[0]

    # Hiệu số giữa các cạnh mới (a-c, b-d) và các cạnh cũ (a-b, c-d)
    old_edges = distance(cities[a], cities[b]) + distance(cities[c], cities[d])
    new_edges = distance(cities[a], cities[c]) + distance(cities[b], cities[d])
    delta_e = new_edges - old_edges

    # Tạo nghiệm láng giềng bằng cách đảo ngược đoạn từ i đến j
    neighbor_tour = tour[:]
    neighbor_tour[i:j+1] = reversed(neighbor_tour[i:j+1])

    return neighbor_tour, delta_e

# Giả sử có 4 thành phố với tọa độ (x, y)
cities = [(0, 0), (1, 5), (5, 5), (5, 0)]
current_tour = [0, 1, 2, 3] # Lộ trình ban đầu

# 1. Tính khoảng cách hiện tại
current_dist = compute_tsp_distance(current_tour, cities)
print(f"Quãng đường ban đầu: {current_dist}")

# 2. Sinh một nghiệm láng giềng
neighbor, diff = get_neighbor(current_tour, cities)
print(f"Lộ trình láng giềng: {neighbor}")
print(f"Quãng đường thay đổi (Delta): {diff}")
print(f"Quãng đường mới: {current_dist + diff}")